//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimilarTable
    {
        public string table_schema { get; set; }
        public string table_name { get; set; }
        public Nullable<int> num_columns { get; set; }
        public string first_column_name { get; set; }
        public string midline_column_name { get; set; }
        public string last_column_name { get; set; }
        public string table_name_suffix { get; set; }
    }
}
