//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetailsForExcelImport0325
    {
        public int ItemLNum { get; set; }
        public string DocNumber { get; set; }
        public Nullable<int> Region { get; set; }
        public string FUND { get; set; }
        public string OrgCode { get; set; }
        public string BA { get; set; }
        public string TitleField { get; set; }
        public Nullable<int> BBFY { get; set; }
        public Nullable<int> EBFY { get; set; }
        public string FC { get; set; }
        public Nullable<int> OC { get; set; }
        public Nullable<int> CE { get; set; }
        public string ProjNum { get; set; }
        public string AGRE_BLDG { get; set; }
        public string BUILDING { get; set; }
        public string SYS_LOC { get; set; }
        public string VEH_TAG { get; set; }
        public string WI { get; set; }
        public string VENDNAME { get; set; }
        public string VEND_CD { get; set; }
        public string ACTG_PD { get; set; }
        public Nullable<decimal> Total_Line { get; set; }
        public Nullable<decimal> COM { get; set; }
        public Nullable<decimal> PREPAY { get; set; }
        public Nullable<decimal> UDO { get; set; }
        public Nullable<decimal> ACCR { get; set; }
        public Nullable<decimal> UDO_DO { get; set; }
        public Nullable<decimal> PENDPYMT { get; set; }
        public Nullable<decimal> PYMTS_TRAN { get; set; }
        public Nullable<decimal> PYMTS_CONF { get; set; }
        public Nullable<decimal> HOLDBACKS { get; set; }
        public string ORDACTG { get; set; }
        public string LAST_PAID { get; set; }
        public string LineInfo { get; set; }
        public string TeamCode { get; set; }
        public string LeaseNo { get; set; }
        public Nullable<int> ACCTLNUM { get; set; }
    }
}
