//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFundAllowance
    {
        public int AllowRecordID { get; set; }
        public string FiscalYear { get; set; }
        public decimal Amount { get; set; }
        public string MonthList { get; set; }
        public int MonthCount { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
    }
}
