//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFS_BusinessLine
    {
        public int BusinessLineCode { get; set; }
        public string BusinessLine { get; set; }
        public string BL_CD { get; set; }
        public string BLDesc { get; set; }
    }
}
