//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFS_PGVXX_Formula
    {
        public string FiscalYear { get; set; }
        public string BookMonth { get; set; }
        public string OrgCode { get; set; }
        public string ReportFunctionCode { get; set; }
        public decimal PercentValue { get; set; }
    }
}
