//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFS_CostElementTypes
    {
        public string COST_ELEM_CD { get; set; }
        public string COST_ELEM_DESC { get; set; }
        public bool IS_AWARD_CALC { get; set; }
        public bool IS_TRAINING_CALC { get; set; }
    }
}
