//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOIMain_0722
    {
        public int OItemID { get; set; }
        public int LoadID { get; set; }
        public int OIType { get; set; }
        public string DocType { get; set; }
        public string DocNumber { get; set; }
        public bool JustificationRequired { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> EarliestDate { get; set; }
        public Nullable<System.DateTime> LatestDate { get; set; }
        public string AcctPeriod { get; set; }
        public Nullable<decimal> TotalLine { get; set; }
        public Nullable<decimal> COM { get; set; }
        public Nullable<decimal> UDO { get; set; }
        public Nullable<decimal> UDOShouldBe { get; set; }
        public Nullable<decimal> DO { get; set; }
        public Nullable<decimal> DOShouldBe { get; set; }
        public Nullable<decimal> ACCR { get; set; }
        public Nullable<decimal> UDO_DO { get; set; }
        public Nullable<decimal> PENDPYMT { get; set; }
        public Nullable<decimal> TotalOrder { get; set; }
        public Nullable<decimal> TotalOrderPercent { get; set; }
        public Nullable<decimal> PYMTS_TRAN { get; set; }
        public Nullable<decimal> PYMTS_CONF { get; set; }
        public Nullable<decimal> HOLDBACKS { get; set; }
        public Nullable<System.DateTime> ExpectedCompDate { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<System.DateTime> LastPaid { get; set; }
        public string ContractingOfficer { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string AwardNumber { get; set; }
        public string StatusField { get; set; }
        public Nullable<decimal> PREPAY { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string OrgCodeBySource { get; set; }
        public string OrgSymBySource { get; set; }
        public string LeaseNum { get; set; }
        public string AccrualType { get; set; }
        public string BABySource { get; set; }
        public string IDBySource { get; set; }
        public string TypeOfBalance { get; set; }
        public string Category { get; set; }
        public string EstimatedAccrual { get; set; }
        public string ItemInfo { get; set; }
        public string LeaseNo { get; set; }
    }
}
