//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOIOrganization
    {
        public int LoadID { get; set; }
        public int OItemID { get; set; }
        public string DocNumber { get; set; }
        public string ULOOrgCode { get; set; }
        public string ResponsibleOrg { get; set; }
        public int ReviewerUserID { get; set; }
        public int Status { get; set; }
        public string Comments { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
