//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOILease
    {
        public int LoadID { get; set; }
        public int OItemID { get; set; }
        public int ItemLNum { get; set; }
        public string DocNumber { get; set; }
        public string LeaseNo { get; set; }
        public string TypeOfLease { get; set; }
        public string ProjectNo { get; set; }
        public string ProspectusNo { get; set; }
        public Nullable<System.DateTime> LeaseEffectiveDate { get; set; }
        public Nullable<System.DateTime> LeaseExpirationDate { get; set; }
        public Nullable<System.DateTime> LeaseAnniversaryDate { get; set; }
        public Nullable<decimal> AnnualRent { get; set; }
        public Nullable<decimal> CurrProjectedAnnualRent { get; set; }
        public Nullable<decimal> NewProjectedAnnualRent { get; set; }
        public Nullable<decimal> OldProjectedAnnualRent { get; set; }
        public Nullable<decimal> RSF { get; set; }
        public string ProjectedLeaseNo { get; set; }
        public string ProjectedProjectNo { get; set; }
        public string ProjectedProspectusNo { get; set; }
        public Nullable<System.DateTime> ProjectedsLeaseEffectiveDate { get; set; }
        public Nullable<decimal> ProjectedAnnualRent { get; set; }
        public Nullable<decimal> ProjectedRSF { get; set; }
        public Nullable<decimal> FY_2_CPI_EscalationExpense { get; set; }
        public Nullable<decimal> FY_1_CPI_EscalationExpense { get; set; }
        public Nullable<decimal> FY_CPI_EscalationProjection { get; set; }
        public Nullable<decimal> FY_1_EscalationExpenseDiff { get; set; }
        public Nullable<decimal> FY_EscalationExpenseDiff { get; set; }
        public Nullable<decimal> FY_1_EscalationExpensePercIncrease { get; set; }
        public Nullable<decimal> FY_EscalationExpensePercIncrease { get; set; }
        public Nullable<decimal> AnnualIncreaseOfAction { get; set; }
        public Nullable<System.DateTime> EffectiveDateOfAction { get; set; }
        public Nullable<System.DateTime> FYEndDate { get; set; }
        public Nullable<int> NumberDaysProratedMonth { get; set; }
        public Nullable<decimal> MonthlyIncrease { get; set; }
        public Nullable<int> TotalMonths { get; set; }
        public Nullable<decimal> TotalMonthsCatchUp { get; set; }
        public Nullable<int> DaysProrated { get; set; }
        public Nullable<decimal> TotalDayCatchUp { get; set; }
        public Nullable<decimal> TotalCatchUp { get; set; }
        public Nullable<int> AccrualAmt { get; set; }
        public string FY_FirstHalfTaxInvoiceDatePeriod { get; set; }
        public string FY_SecondHalfTaxInvoiceDatePeriod { get; set; }
        public string FY1_FirstHalfTaxInvoiceDatePeriod { get; set; }
        public Nullable<decimal> FY_FirstHalfTaxInvoiceTotalTaxBill { get; set; }
        public Nullable<decimal> FY_SecondHalfTaxInvoiceTotalTaxBill { get; set; }
        public Nullable<decimal> FY1_FirstHalfTaxInvoiceTotalTaxBill { get; set; }
        public Nullable<decimal> FY_TaxBillReceiptTotal { get; set; }
        public Nullable<int> FY_FirstHalfTaxInvoiceNoOfMonReimb { get; set; }
        public Nullable<int> FY_SecondHalfTaxInvoiceNoOfMonReimb { get; set; }
        public Nullable<int> FY1_FirstHalfTaxInvoiceNoOfMonReimb { get; set; }
        public Nullable<int> FY_TaxBillReceiptNoOfMonReimb { get; set; }
        public Nullable<decimal> FY_TaxBaseYearReimb { get; set; }
        public Nullable<decimal> FY_NetAmountReimb { get; set; }
        public Nullable<decimal> FY_PercOfGovOccupancyReimb { get; set; }
        public Nullable<decimal> FY_AmountDueLessorReimb { get; set; }
        public string FY1_SecondHalfTaxInvoiceDatePeriod { get; set; }
        public string FY2_FirstHalfTaxInvoiceDatePeriod { get; set; }
        public Nullable<decimal> FY1_SecondHalfTaxInvoiceTotalTaxBill { get; set; }
        public Nullable<decimal> FY2_FirstHalfTaxInvoiceTotalTaxBill { get; set; }
        public Nullable<decimal> FY1_TaxBillReceiptTotal { get; set; }
        public Nullable<int> FY1_SecondHalfTaxInvoiceNoOfMonReimb { get; set; }
        public Nullable<int> FY2_FirstHalfTaxInvoiceNoOfMonReimb { get; set; }
        public Nullable<int> FY1_TaxBillReceiptNoOfMonReimb { get; set; }
        public Nullable<decimal> FY_FirstHalfTaxInvoiceReimbAmt { get; set; }
        public Nullable<decimal> FY_SecondHalfTaxInvoiceReimbAmt { get; set; }
        public Nullable<decimal> FY1_FirstHalfTaxInvoiceReimbAmt { get; set; }
        public Nullable<decimal> FY_TaxBillReceiptReimbAmt { get; set; }
        public Nullable<decimal> FY1_SecondHalfTaxInvoiceReimbAmt { get; set; }
        public Nullable<decimal> FY2_FirstHalfTaxInvoiceReimbAmt { get; set; }
        public Nullable<decimal> FY1_TaxBillReceiptReimbAmt { get; set; }
        public Nullable<decimal> FY1_TaxBaseYearReimb { get; set; }
        public Nullable<decimal> FY1_NetAmountReimb { get; set; }
        public Nullable<decimal> FY1_PercOfGovOccupancyReimb { get; set; }
        public Nullable<decimal> FY1_AmountDueLessorReimb { get; set; }
        public Nullable<decimal> FY2_RETEscalationProjectionNetIncr { get; set; }
        public Nullable<decimal> FY2_RETEscalationProjectionRevNetIncr { get; set; }
        public Nullable<decimal> FY2_RETEscalationProjectionPercIncr { get; set; }
        public Nullable<decimal> FY2_RETEscalationProjectionRevPercIncr { get; set; }
        public Nullable<decimal> FY2_RETEscalationProjectionAccr { get; set; }
        public Nullable<decimal> FY2_RETEscalationProjectionRevAccr { get; set; }
        public Nullable<System.DateTime> CurrAuditEndDate { get; set; }
        public Nullable<decimal> EstablishedCurrentProjAnnualRent { get; set; }
        public Nullable<decimal> EstablishedNewProjAnnualRent { get; set; }
        public Nullable<decimal> EstablishedOldProjAnnualRent { get; set; }
        public Nullable<decimal> EstablishedAnnualIncreaseOfAction { get; set; }
        public Nullable<System.DateTime> EstablishedEffectiveDateOfAction { get; set; }
        public Nullable<System.DateTime> EstablishedFYEndDate { get; set; }
        public Nullable<int> EstablishedNumberDaysProratedMonth { get; set; }
        public Nullable<decimal> EstablishedAccrualAmt { get; set; }
        public Nullable<decimal> EstablishedMonthlyIncrease { get; set; }
        public Nullable<int> EstablishedTotalMonths { get; set; }
        public Nullable<decimal> EstablishedTotalMonthsCatchUp { get; set; }
        public Nullable<int> EstablishedDaysProrated { get; set; }
        public Nullable<decimal> EstablishedTotalDayCatchUp { get; set; }
        public Nullable<decimal> EstablishedTotalCatchUp { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<bool> PriorYearHistoryAttached { get; set; }
        public Nullable<bool> FileContainsSupport { get; set; }
        public Nullable<int> ReviewerReasonCode { get; set; }
        public string Comments { get; set; }
        public Nullable<int> AccrualType { get; set; }
        public Nullable<int> AccrualTypeAction { get; set; }
        public Nullable<int> FY_YY_Est { get; set; }
        public Nullable<int> FY_YY { get; set; }
        public Nullable<decimal> TotalDO { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> RevisedNewProjAnnualRent { get; set; }
        public string TeamCode { get; set; }
        public string SortCode { get; set; }
        public Nullable<int> StateID { get; set; }
        public string Signature1 { get; set; }
        public string Signature2 { get; set; }
        public Nullable<System.DateTime> SignatureDate1 { get; set; }
        public Nullable<System.DateTime> SignatureDate2 { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<decimal> TotalDOShouldBe { get; set; }
        public Nullable<int> ReasonForDelayID { get; set; }
        public string OtherReasonForDelay { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> EffectiveDateOfAction5 { get; set; }
    }
}
