//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOIDocAttachment
    {
        public string DocNumber { get; set; }
        public int DocID { get; set; }
        public string LinesInfo { get; set; }
        public string Comment { get; set; }
        public bool Active { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> UpdateUser { get; set; }
    }
}
