//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOIAccrualTypeAction
    {
        public int AccrualTypeActionCode { get; set; }
        public string AccrualActionTypeDesc { get; set; }
        public Nullable<int> AccrualTypeCode { get; set; }
    }
}
