//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReassignRequest
    {
        public int RequestID { get; set; }
        public int OItemID { get; set; }
        public string ULOOrgCode { get; set; }
        public int ItemLNum { get; set; }
        public int ReviewerUserID { get; set; }
        public string Responsibility { get; set; }
        public string RerouteOrgCode { get; set; }
        public string RerouteOrganization { get; set; }
        public Nullable<int> RerouteUserID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> VerifyDate { get; set; }
        public string Comments { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
