//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDocAttachment
    {
        public int DocID { get; set; }
        public string DocNumber { get; set; }
        public string RWA { get; set; }
        public Nullable<int> RWALineNum { get; set; }
        public string Title { get; set; }
        public string AwardNumber { get; set; }
        public string LeaseNum { get; set; }
        public Nullable<int> ItemLNum { get; set; }
        public string ULOOrgCode { get; set; }
        public string BA { get; set; }
        public string ProjNum { get; set; }
        public string BUILDING { get; set; }
        public string VENDNAME { get; set; }
    }
}
