//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserIDRef
    {
        public int OldUserID { get; set; }
        public string OldEmail { get; set; }
        public string NewEmail { get; set; }
        public Nullable<int> NewUserID { get; set; }
    }
}
