//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSA.UnliquidatedObligations.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public int RegionId { get; set; }
        public int ZoneId { get; set; }
        public string RegionNumber { get; set; }
        public string RegionName { get; set; }
    
        public virtual Zone Zone { get; set; }
    }
}
