//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSA.UnliquidatedObligations.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ULO()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int RecordID { get; set; }
        public Nullable<int> RegionNumber { get; set; }
        public int OwnerUserID { get; set; }
        public Nullable<decimal> TotalLine { get; set; }
        public Nullable<bool> ValidStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual User User { get; set; }
    }
}
