//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSA.UnliquidatedObligations.BusinessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialActivity
    {
        public int FinancialActivityId { get; set; }
        public int UloId { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string ActivityType { get; set; }
        public string ReferenceNumber { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAtUtc { get; set; }
    
        public virtual UnliquidatedObligation UnliquidatedObligation { get; set; }
    }
}
