//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSA.UnliquidatedObligations.BusinessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PdnAttribute
    {
        public int PdnAttributeId { get; set; }
        public string PegasysDocumentNumber { get; set; }
        public Nullable<int> RegionId { get; set; }
        public System.DateTime CreatedAtUtc { get; set; }
        public bool IsExcluded { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
