//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSA.UnliquidatedObligations.BusinessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewStat
    {
        public int ReviewId { get; set; }
        public Nullable<int> EasiCnt { get; set; }
        public Nullable<int> RetaCnt { get; set; }
        public Nullable<int> PegasysObligations192Cnt { get; set; }
        public Nullable<int> PegasysObligations442Cnt { get; set; }
        public Nullable<int> UloCnt { get; set; }
        public Nullable<int> PersonCnt { get; set; }
        public Nullable<int> GroupCnt { get; set; }
        public Nullable<int> SystemCnt { get; set; }
        public Nullable<int> PreAssignmentCnt { get; set; }
        public Nullable<int> TheCloserCnt { get; set; }
    }
}
