//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSA.UnliquidatedObligations.BusinessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnliqudatedObjectsWorkflowQuestion
    {
        public int UnliqudatedWorkflowQuestionsId { get; set; }
        public int WorkflowId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UserId { get; set; }
        public string Answer { get; set; }
        public string Justification { get; set; }
        public string Comments { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Workflow Workflow { get; set; }
    }
}
