//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSA.UnliquidatedObligations.BusinessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnliquidatedObligation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnliquidatedObligation()
        {
            this.Notes = new HashSet<Note>();
            this.Workflows = new HashSet<Workflow>();
        }
    
        public int UloId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public int PegasysObligationId { get; set; }
        public int ReviewId { get; set; }
        public string Organization { get; set; }
        public string Fund { get; set; }
        public string Prog { get; set; }
        public string DocType { get; set; }
        public string PegasysDocumentNumber { get; set; }
        public int ItemsLineNumber { get; set; }
        public int AccountingLineNumber { get; set; }
        public string PegasysTitleNumber { get; set; }
        public string BBFY { get; set; }
        public string EBFY { get; set; }
        public string Acty { get; set; }
        public int OC { get; set; }
        public string SOC { get; set; }
        public string Project { get; set; }
        public string Agreement { get; set; }
        public string ContractNum { get; set; }
        public string Bldg { get; set; }
        public string SysLoc { get; set; }
        public string VehTag { get; set; }
        public int WI { get; set; }
        public string LeaseNumber { get; set; }
        public string VendorName { get; set; }
        public string ActgPd { get; set; }
        public string TotalLine { get; set; }
        public string Commitments { get; set; }
        public string Prepayments { get; set; }
        public string UndelOrders { get; set; }
        public string Rcpt { get; set; }
        public string Accrual { get; set; }
        public string TotalDO { get; set; }
        public string TotalUDOAndDO { get; set; }
        public string PendPayments { get; set; }
        public string PymtsInTransit { get; set; }
        public string PymtsConfirmed { get; set; }
        public string Holdbacks { get; set; }
        public string TAFS { get; set; }
        public string DUNSNum { get; set; }
        public Nullable<System.DateTime> DateOfLastActivity { get; set; }
        public Nullable<int> DaysSinceLastActivity { get; set; }
        public Nullable<System.DateTime> DateOfFirstActivity { get; set; }
        public Nullable<int> DaysSinceFirstActivity { get; set; }
        public string TradingPartnerType { get; set; }
        public string VendorAgencyCode { get; set; }
        public string VendorBureauCode { get; set; }
        public Nullable<bool> Valid { get; set; }
        public string Status { get; set; }
        public string AwardNbr { get; set; }
        public string ContractingOfficersName { get; set; }
        public string ReasonIncludedInReview { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        public virtual PegasysObligation PegasysObligation { get; set; }
        public virtual Review Review { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workflow> Workflows { get; set; }
    }
}
