//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSA.UnliquidatedObligations.BusinessLayer.Data
{
    using System.Collections.Generic;

    public partial class WorkflowDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowDefinition()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int WorkflowDefinitionId { get; set; }
        public string WorkflowKey { get; set; }
        public int Version { get; set; }
        public string DescriptionJson { get; set; }
        public string DescriptionXml { get; set; }
        public string WorkflowDefinitionName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
