//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSA.UnliquidatedObligations.BusinessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowView
    {
        public int WorkflowViewId { get; set; }
        public int WorkflowId { get; set; }
        public string UserId { get; set; }
        public System.DateTime ActionAtUtc { get; set; }
        public string ViewAction { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Workflow Workflow { get; set; }
    }
}
