//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignmentRule
    {
        public string DocType { get; set; }
        public string AcctPeriod { get; set; }
        public Nullable<decimal> UDOMin { get; set; }
        public Nullable<decimal> UDOMax { get; set; }
        public string Responsibility { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
