//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttachmentRequirement
    {
        public string PegasysDocType { get; set; }
        public string Notes { get; set; }
        public string TotalDocTypeDesc { get; set; }
        public string DODocTypeDesc { get; set; }
    }
}
