//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocRWA
    {
        public string DocNumber { get; set; }
        public int ItemLNum { get; set; }
        public string RWA { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
