//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFundAllowanceByOrg
    {
        public string FiscalYear { get; set; }
        public string BookMonth { get; set; }
        public string OrgCode { get; set; }
        public decimal PercentByOrg { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
    }
}
