//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFS_ReportConfig
    {
        public int OrderNumber { get; set; }
        public string Name { get; set; }
        public string FuncCode { get; set; }
        public string OCCode { get; set; }
        public string OCNumber { get; set; }
        public string CaptionStyle { get; set; }
        public bool LoadIncome { get; set; }
        public string AddAdjustment { get; set; }
    }
}
