//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReviewerReasonCode
    {
        public int ReasonCodeID { get; set; }
        public string ReasonCodeDesc { get; set; }
        public string ShortDesc { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
