//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTempUser
    {
        public int UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string RoleCode { get; set; }
        public bool Active { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleInitial { get; set; }
        public string Organization { get; set; }
        public string Phone { get; set; }
        public short DefaultApplication { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> SysAdmin { get; set; }
    }
}
